name: GitHub Actions
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  setup-test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
    steps:
    - uses: actions/checkout@master
    - name: Install jumanpp
      run: brew install jumanpp
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pip install
      run:
        pip install wheel
    - name: test
      run: python setup.py test

